### ISSUE TITLE
As a PM/Tech Lead, I would like to create a Test Plan for Milestone 1

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#178]
Test plan must include manual/functional tests for all the business and technical requirements.

All Business requirements and some Technical requirements are outlined in the backlog.
All technical requirements are outlined in the 14C Technical requirements document.

TODO: Other technical requirements outlined in the 14C Technical requirements document must be made in to stories.

Acceptance Criteria:
- [x] Spreadsheet template finalized
- [x] QA process definition
- [ ] Assigned steps/duties per process
