### ISSUE TITLE
As a vendor developer, I must demonstrate that 14C application works with DB2

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#184]
As a vendor developer, I would like to add API code that works with DB2:
Existing API code works with PostgreSQL. Newly written  API code should work with DB2 SQL.
New code must not eliminate existing code (basically use Object Oriented and Dependency Injection principles).

**Steps**:
1) Use NuGet package for DB2/EF. 
https://www.nuget.org/packages/EntityFramework.IBM.DB2/
Ensure EF 64 bit version and EF 32 bit version can co-exist & document steps if any.

Ensure EF6 DB2 Migrations NUGet package is installed as well.
https://www.nuget.org/packages/System.Data.DB2.EntityFramework.Migrations/
Refer to this link as well:
https://db2ef6migrations.codeplex.com/

2) Write new DB2 API implementation (based on but without modifying existing PostgreSQL implementation). Discuss code implementation strategy/patterns with WHD/18F prior to starting. 

Assumptions
- NuGet package works with existing codebase
- Data Types and data retrieval does not require major modifications to codebase
- Review licensing on NuGet packages for EF and DB2 adapter

**Acceptance Criteria**:
- [x] story depends on #233 
- [x] Demonstrate DB2 EF code first migrations should deploy to DB2 server
- [x] Demonstrate *all* API calls work successfully through unit tests. Use MOQ or Effort for EF6 mocking. Talk to WHD/18F prior to choosing MOQ/Effort. Unit Tests associated?  Code coverage already exists, leverage db seeding scripts to test access to DB2
- [x] Document 32 bit vs 64 bit package restore issues (if any).

**Comment by mgwalker** [comment]
You can download [Db2 Express-C](https://www.ibm.com/developerworks/downloads/im/db2express/) for free.  For ease of installation and configuration, I'd suggest the [Db2 docker image](https://hub.docker.com/r/ibmcom/db2express-c/) for development, rather than mucking about with settings directly on dev machines.

**Comment by binwang89** [comment]
The DB2 upgraded version will be DB2 10.5 and DEV environment has been upgraded to 10.5.  
The Prod environment upgrade timeline is still pending.

**Comment by mmurthydol** [comment]
@dciceman @klinden Thoughts for UUIDs + EF Code first migration DB2 issue

Are we always generating UUIDs in code through New.Guid()? if so, does var char data type matter in DB? 

                                 PostgreSQL                      DB2                                    Comment
DB Type                   "character varying"           BIT DATA (or) VARCHAR    Use varchar

Info below useful only for DB First (not our scenario):
TRIM(CHAR(HEX(GENERATE_UNIQUE())))

**Comment by klinden** [comment]
@mmurthydol @binwang89 @dciceman 

Thanks, Madhu. David and I just talked and we are going to attempt to convert all the Ids to strings in the code to get around this issue. As you mentioned, since we are using Guid.NewGuid() in the code this shouldn't be too difficult of an effort. The ids were just being used for foreign key relationships so we should only need to make changes to the models, not any of the business logic.

**Comment by mmurthydol** [comment]
[14c.txt](https://github.com/18F/dol-whd-14c/files/1335781/14c.txt)
@dciceman @klinden David, I followed up after our pairing and there is a way we can likely make this work. Please ping me when start work, I will see if I can get out of my meetings to sync up quickly with you. (a) let's continue our track a little bit but I have a feeling we might run in to some road blocks - having taken a look at the GitHub code for the migrations Nuget (b) Most likely viable approach is to create a new MigrationsDb2 folder and create new files that don't care about all the history. I will provide a postgresql schema that we can use to write the DB2 CreateTable without all the complicated migrations that we have because of postgresql history.  Talking about this might be simpler but you have the info to think about to get unblocked if we don't sync up early enough tomorrow. Again please ping me when you start work.
[14c.txt](https://github.com/18F/dol-whd-14c/files/1335780/14c.txt)

**Comment by mgwalker** [comment]
@mmurthydol Your comment made this pop into my head: is migration important ***at all***?  Since the 14(c) app from last year never went into production, there shouldn't be any *real* data in postgres anywhere, right?  So there shouldn't be any need to migrate any of that existing data?  It should be safe to drop it all.

(Feel free to completely disregard my question based on y'all's conversations earlier.  I'm not as deep on this as y'all are, but looking at it from the outside, it just seems like "migration" of existing data or databases isn't really a concern.)

**Comment by mmurthydol** [comment]
@mgwalker I paired with David today and am suggesting exactly that - to just write the code from scratch without needing to make all the complicated Migration History code to work for DB2. If IBM or someone actually supported EF6 CodeFirst completely, none of this would be an issue. I verified today there is no official support for code first even with a license, checked the Nuget Migrations code to understand its limitations, to see if there was any easy way to salvage the work done thus far - those are the options (a) & (b). Most likely yield is to disregard migrations and consolidate all changes in to CreateTable. So yes wouldn't be surprised you'd think of it after reading my comment 'cos that is option (b) :) Thanks for the late night comment!

**Comment by mmurthydol** [comment]
@dciceman link below lists the operations supported by the DB2 migrator. Might quickly try (a) by ensuring that our code only uses supported operations. Might be able to move past the key_update migration file...

https://github.com/bubibubi/db2ef6migrations/blob/master/System.Data.DB2.EntityFramework.Migrations/DB2MigrationSqlGenerator.cs

**Comment by jmmcnj** [comment]
reopening to add user stories for work in flight, promoting to epic and putting those stories underneath

**Comment by dciceman** [comment]
For the task "Document 32 bit vs 64 bit package restore issues (if any).", I found only one package and it didn't mention 32 bit or 64 bit.
