### ISSUE TITLE
As a User I would like to be able to upload valid file (types/sizes) attachments through UI.

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#197]
@PrabhakarThummalaDOL  Please test to determine scope of problem to prioritize.

#629 is a defect from QA of this story...

Please implement client side validation per requirements below. App currently doesn't validate for all said file types below. App also doesn't validate for file sizes.  Use design/prototype from UX team for input to this user story #343 (visual design) & #290

Error message needed for invalid type and/or size
> Note: HTML templates for the feedback messages are provided in the comments below.

**Acceptance Criteria:**
@stevenmyket Harun implemented most of the ones below except for the top two items I believe. Please check.

  - [ ] Demonstrate only valid types/sizes are allowed. Current implementation has defects. Refer to #343 (not #262) for updated valid file types/requirements. #262 might contain the verbiage needed for validation. @stevenmyket Talk to DOL to make sure you understand what is required.
 - [x] server side API needs to make changes as well. @dciceman if not already, please update web.config
from
<setParameter name="AllowedFileNamesRegex" value="^.*\.(doc|docx|xls|pdf|jpg|jpeg|png|csv)$" />
 to
<setParameter name="AllowedFileNamesRegex" value="^.*\.(pdf|jpg|jpeg|png)$" />

 - [x] Delete button for uploaded file launches a confirmation modal, as shown in the UXPin prototype
 - [x] Demonstrate app doesn't work for invalid types/sizes. (5MB I believe. see #290)
 - [x] Demonstrate  UI validation (client side validation) for invalid types/sizes.
 - [ ] For accessibility requirements see #198

**Comment by mmurthydol** [comment]
@oghaffari : Need help. I can't see my @ alias in the ZenHub drop down, Thanks, Madhu

**Comment by oghaffari** [comment]
@mmurthydol: Which drop down in particular?

**Comment by mmurthydol** [comment]
@oghaffari When I type @m the dropdown selection to choose from a list of names doesn't contain my name. I wanted to write a note to myself - may be that's not possible?

**Comment by oghaffari** [comment]
I think you're on to something, @mmurthydol. I tried to add myself and had no luck!

**Comment by mmurthydol** [comment]
@binwang89 Could you please follow up with Liz about valid file types. Right now doc/docx are not listed.
I will update the file sizes.

AIS will need to implement the code changes accordingly.

**Comment by mgwalker** [comment]
This should be implemented on both server and client side

**Comment by mmurthydol** [comment]
Absolutely Greg - Thanks for pointing it out. Added (3) to the acceptance criteria.

**Comment by phirefly** [comment]
Removed ^^ tag because we're linking to the requirements in #290

**Comment by ltsheu** [comment]
CSS/HTML templates have been created for the file upload feedback messages. The CSS has been merged in Sprint/3. The HTML templates have been passed to @davoodharun .

**Comment by jmmcnj** [comment]
@simplyshang will be able to provide links to help harun in what he should be changing

**Comment by jmmcnj** [comment]
@simplyshang will be able to provide links to help harun in what he should be changing

**Comment by ltsheu** [comment]
@davoodharun  New feedback message patterns to be used for File Upload feedback. The CSS will be merged with PR #402

**UPLOAD IN PROGRESS:**

![feedback-progress](https://user-images.githubusercontent.com/31778248/32621703-a6727fe2-c54e-11e7-8963-e6b74a380fcf.PNG)

```
  <div class="dol-feedback-progress">
    <p class="dol-feedback-message">
      <strong>Uploading:</strong> FileName.pdf
    </p>
  </div>
```

**UPLOAD ERROR:**

![feedback-error](https://user-images.githubusercontent.com/31778248/32621829-0ce80486-c54f-11e7-9f8d-6ea07c8208b4.PNG)

```
  <div class="dol-feedback-error">
      <p class="dol-feedback-message">
        <strong>File size too large.</strong> FileName.pdf was not updated. Files cannot be larger than 5MB.
      </p>
  </div>
```
**LIST OF UPLOADED FILES (this is basically the "success" feedback for file upload)**

![uploaded-files](https://user-images.githubusercontent.com/31778248/32621867-3c170608-c54f-11e7-830a-aeb50345e638.png)

```
  <ul class="dol-uploaded-files">
    <li>
      <strong>Uploaded:</strong> FileName.pdf
      <button class="red-button">Delete<span class="hide"> FileName.pdf</span></button>
    </li>
    <li>
        <strong>Uploaded:</strong> FileName.pdf
        <button class="red-button">Delete<span class="hide"> FileName.pdf</span></button>
    </li> 
    <li>
        <strong>Uploaded:</strong> FileName.pdf
        <button class="red-button">Delete<span class="hide"> FileName.pdf</span></button>
    </li>   
  </ul>
```

**Comment by mmurthydol** [comment]
@davoodharun https://github.com/18F/dol-whd-14c/issues/629 is a defect story for this story https://github.com/18F/dol-whd-14c/issues/197

Moving 197 from awaiting acceptance to in progress.

**Comment by EStriegel** [comment]
@binwang89 Assigning to you to review accessibility.  I have validated the other criteria.  You can move to `Done` once accessibility is confirmed.

**Comment by binwang89** [comment]
@EStriegel  hi, Liz, I tested this feature and found the error messages receive no focus, hence cannot be read by assistive technology (JAWS).   This is the same issue as user story #536  
Please see the screenshot below.  When there is error upload the file, the focus is skip the error message and jump to next interactive item. 


![image](https://user-images.githubusercontent.com/25330625/36122803-bd597aa2-1018-11e8-94d2-2c918c3cf7c2.png)

**Comment by mmurthydol** [comment]
Michelle, please add this comment to your comment above.

@davoodharun 
Desired behavior: Upon file size too large error, from accessibility perspective, focus must be placed on the file size error message and subsequent tabbing should let focus go to the next text box as indicated by the second arrow. #536 has the fix: add tabindex=0 to the error message.

**Comment by binwang89** [comment]
@EStriegel @mmurthydol Tested this issue again, it is partially fixed. I will assign it to @NathayaMDOL .

Issue Steps:
when there is error message for the upload the file, the focus will focus to the error message and user be able to deleted it from the popup confirming message box. However, after deleted the file. The focus can moved to next text box, but the popup box won’t be able to closed by keyboard ( tabbing). 

Desired behavior: from accessibility perspective, focus must be placed on the “X” of popup confirming box then hit “Enter” to close the box, then focus will jump to next interactive item (Text box). 
Please see the screenshot below, the focus has jump to next item (arrow show), but the popup box is still there. 


![image](https://user-images.githubusercontent.com/25330625/43052301-5c56dd5a-8df2-11e8-9fc7-974a779a1c31.png)

**Comment by NathayaMDOL** [comment]
@binwang89 ,
Per our walked through the demo site for this issue yesterday, we found more issue after deleted the attached file need to be fixed also. Screenshot below.
![197-wage data-deleted attached file showing failed](https://user-images.githubusercontent.com/40499717/43266123-876333ae-90b8-11e8-832d-cbac03e466a3.png)

-Nathaya

**Comment by binwang89** [comment]
@NathayaMDOL Thank you for upload the screenshot.  As we talked, when you fixing the popup confirmation message issue, please also check the error message ( Failed to delete file), why this error message was displayed after we delete the file successfully. it should only be displayed when user failed to delete the file. Thanks

**Comment by binwang89** [comment]
@NathayaMDOL please check all spots for upload file to make sure the popup confirming message box is section 508 compliance.  please reference to this user story #115 ( for all screenshot).

**Comment by NathayaMDOL** [comment]
The story#197 and #115 have been fixed and pushed to Dev. Let me know if any changes.
Branch "whd-aqa-197-nmankong-508-attachment-delete-function". 
![popup message tab sequence](https://user-images.githubusercontent.com/40499717/43977808-37494294-9cb3-11e8-9b1f-baf81e2ac491.png)
![1dashboardpopup](https://user-images.githubusercontent.com/40499717/43977798-3020d5e0-9cb3-11e8-84f1-68cab11dd47e.PNG)
![2attachmentfilepopup](https://user-images.githubusercontent.com/40499717/43977821-3d9b6ed8-9cb3-11e8-9281-a9f8e249d20b.PNG)
![3resendemail](https://user-images.githubusercontent.com/40499717/43977827-3f8edf5e-9cb3-11e8-84ea-7da92337d3b1.PNG)
![4resetpassword](https://user-images.githubusercontent.com/40499717/43977829-4196541c-9cb3-11e8-9151-f0b77765e627.PNG)
![5updateuseraccount](https://user-images.githubusercontent.com/40499717/43977834-43272af4-9cb3-11e8-823a-33f34cbdc7e2.PNG)

**Comment by NathayaMDOL** [comment]
For future reference: Regarding to the discussion from email "popup message issue", the team agreed to switch the order of No, Yes button to be Yes, No instead. Screenshot below.

![535-dashboardpopup](https://user-images.githubusercontent.com/40499717/44059066-306435d4-9f1e-11e8-9797-83a1d85ea43c.PNG)
![535-attachmentfilepopup](https://user-images.githubusercontent.com/40499717/44059078-37d4acf4-9f1e-11e8-9c4e-d0d632974cb1.PNG)
![535-updateuseraccount](https://user-images.githubusercontent.com/40499717/44059083-3a2e3cd6-9f1e-11e8-9a8f-d1322fb7b871.PNG)

**Comment by binwang89** [comment]
move to done
