### ISSUE TITLE
As an Employer, I would like to enter Wage Data with ease

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#210]
Current 14C UI for Wage Data entry is not Ux Friendly. See picture below. 
![14c_wagedata](https://user-images.githubusercontent.com/25183303/29734675-9484729a-89c1-11e7-9399-cc7fe11359a7.jpg)

**TASKS**:
- [x] Design UX design to provide user friendly data entry in conjunction with DOL. 
       Please see Madhu's comments for some user friendly possibilities.
- [x] UI need to be revised to be more data entry friendly.

**ACCEPTANCE CRITERIA**:
- [x] Provide UX Design to be approved by WHD.
- [x] Document UX Design as part of this story (design implemented in #244).
- [x] Document accessibility, test cases identified during design.

**Comment by EStriegel** [comment]
Also, see text edits document (pg 14) for text changes to each column.
[Online App - Needed text edits.pdf](https://github.com/18F/dol-whd-14c/files/1267265/Online.App.-.Needed.text.edits.pdf)

**Comment by mgwalker** [comment]
Accessibility acceptance criteria:
- [ ] all wage data text boxes can be reached by keyboard navigation
- [ ] all text boxes have the appropriate `type` attribute
- [ ] all text boxes have appropriate labels

**Comment by binwang89** [comment]
User Story #198 has been updated with accessibility acceptance criteria for all UI user stories.

**Comment by mmurthydol** [comment]
I see following alternatives  technically for UX implementation:
1)	Popup to add the wage data with forced return the original calling page.
2)	New page to add the wage data with forced return the original calling page.

In either case, wage data that is entered would be displayed  in the original calling page in the form of a grid/table (each row will have edit/delete functionality; add data will be available at top/bottom of the grid).

Surely UX design is involved with choosing one of the above options, placement/presentation of data...?

**Comment by mgwalker** [comment]
Yep, this is exactly the kind of question that user testing is meant to help answer.

**Comment by EStriegel** [comment]
UX design created.  Moving to `Done`
