### ISSUE TITLE
UX Setup Checklist

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#238]
#### Setup Checklist

- [x] Shannon's environment up and running
- [x] Review text changes implemented from Brendan (@estriegel can compile links)
- [x] Prototype setup
- [x] Review Accessibility Criteria w/WCAG 2.0 AA Guidelines
- [ ] Outreach to employers (@simplyshang edit 9/26: Change going into sprint 1; initial outreach may change based on conversation 9/25; possibly starting w/interviews instead of testing to get feedback on account management, Excel upload)

**Comment by simplyshang** [comment]
Here's the link for the prototype: https://preview.uxpin.com/771f403047703ce8241899e0976e57bc30e1c871#/pages/75478246
