### ISSUE TITLE
As a user I would like app and associated infrastructure to be secure so that my data is not subject to security breaches.

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#243]
As a user I would like app and associated infrastructure to be secure so that my data is not subject to security breaches.

Examples of infrastructure: servers, db, network, content switches, folders, web apps/apis, etc.
This epic will implement stories that will ensure all federal security guidelines are complied with.
DOL internally will verify application security compliance using internal tools. 

## Acceptance Criteria
- [ ] All security stories added to backlog with security & "required to go live" label are demonstrated.
- [ ] Application and infrastructure will pass security compliance tests using HP Web Inspect scan audit. These scans will be run in DOL's App unless AIS has its own licenses to the product.

#### Functionality

- [ ] Application/infrastructure is developed/implemented to not have any critical and major security vulnerabilities to be FIPS/NIST/DOL compliant. TODO: DOL to add 5-10 security stories to backlog.
- [ ] Fix all other minor security vulnerabilities as identified and prioritized.

#### Accessibility
N/A.

**Comment by mmurthydol** [comment]
#338 supercedes this story #243. Hence close this story.
