### ISSUE TITLE
a11y Remediation -- Application Info Page

### ISSUE THREAD

**Issue by ltsheu** [18F/dol-whd-14c#276]
Remediate accessibility issues in the Application Info page, according to acceptance criteria noted in #198 

#### Task
- [ ] Fill in a11y scan data in spreadsheet (Application Info tab)
- [ ] Remediate issues in code for Application Info page
- [ ] Check with keyboard navigation
- [ ] Check with screen reader

#### Functionality

No functional changes. The task is to remedy a11y issues.

#### Accessibility
1. Keyboard Accessibility
[ ] 1.1 An interactive element or function can be accessed or activated by keyboard
[ ] 1.2 keyboard "trap" not found
[ ] 1.3 if non-standard keyboard commands are needed and they are documented
[ ] 1.4 TITLE provides information and equivalent information is found through text or visual context
[ ] 1.5 The visual focus can be determined at all times.
[ ] 1.6 focus always appears on the element it is programmatically on.
[ ] 1.7 if focus remains in the modal dialog box until the box is closed.
[ ] 1.8 if focus moves to revealed content OR a description of the content change is provided.
[ ] 1.9 the tab order is logical
2. Web: Forms- Web forms include controls (checkboxes, radio buttons etc.), and editable content (text input, select options etc.).
[ ] 2.1 All form fields and their instructions and cues have HTML (‘Label for’ and ‘ID’ are used or TITLE is descriptive) or ARIA for association.
[ ] 2.2.All 'Label for' and 'ID' are valid code pairs.
[ ] 2.3 All form instructions that are provided by mouse over are available onscreen.
[ ] 2.4 All ARIA form fields have a NAME property that contains all of the instructions.
[ ] 2.5 All ARIA form fields have correct Role, State, and Value properties.
[ ] 2.6 All form controls identify their purpose. (Check if there are multiple form controls with the same visual label).
3. Web: Links and User Controls
Links and/or user controls must have meaningful names that describe the unique destination, function, and/or purpose of the control for assistive technology.
[ ] 3.1 All links have a unique and meaningful description.
[ ] 3.2 All scripted elements have a unique and meaningful description.
4. Web: Images
Web images include interactive images (links, buttons etc.), static images, charts, diagrams, text rendered as an image, etc.
[ ] 4.1 All images have an ALT, TITLE, or ARIA attribute.
[ ] 4.2 All meaningful images with ALT have an equivalent text description.
[ ] 4.3 All decorative images with ALT have ALT="".
[ ] 4.4 All images that contain text with ALT have the same text in the ALT attribute.
[ ] 4.5 CAPTCHA images describe their purpose. (DNA, after the captcha is removed)
[ ] 4.6 All components that have multiple statuses provide their current status
5. Web: Image Maps (if no image map, then DNA)
An image map is a single image that has designated regions or "hotspots" that contain links.Server-side image maps may not be used. Client-side image-maps must be used instead
[ ] 5.1 All image maps are client side
6. Color and Contrast
Color dependence is using color as the sole means to convey information.
There must be contrasting colors/shades at a ratio of 4.5:1 for discerning between background and foreground content.
[ ] 6.1 if color is used but is not the only method to provide information.
[ ] 6.2 if the contrast ratio is 4.5:1 or greater when comparing all background and foreground colors.
Page titles Programmatically identify Page Titles.
[ ] 6.3 There is a meaningful page title in plain language.
7. Time Outs
Messages and/or instructions to the user requesting their response within a given time are typically associated with sites that require a secure login. This includes both server time outs and client side security time outs. If a time out is about to occur, an alert must be posted for at least 20 seconds and the user must have the option to request more time. The alert (often a pop up window) and option to request more time must be keyboard accessible.
[ ] 7.1 The application provides notification before timing out.
[ ] 7.2 The application's time out notification is displayed for at least 20 seconds before timing out.
[ ] 7.3 The application provides user an option to request more time before timing out.
8. Web: Language
A default language must be programmatically identified for each page and for passages that use a language other than the default.
[ ] 8.1 if the correct default language for the page is programmatically set.
[ ] 8.2 if there is not a passage in a language that differs from the default language of the page.
9 Web: Section Headings Headings must be programmatically identified and must match the visual outline level.
[ ] 9.1 All visually apparent headings are programmatically identified with an . ( levels do not need to be correct.)
[ ] 9.2 Programmatic levels on all visually apparent headings match the visual structure.
10. Web: Data Tables (If no table, then DNA)
Data tables are those tables where the information in a cell requires a row or column header to adequately describe the cell's contents.
[ ] 10.1 HTML data tables' row and/or column headers are correctly identified programmatically.
[ ] 10.2 if there are data tables but none of them are images.
[ ] 10.3 if all HTML complex data tables' data cells are associated with their headers programmatically.
[ ] 10.4 if there are complex data tables but none of them are images
11. Web: Style sheet Dependence style sheets are a means to provide visual formatting information to complement a web page's content.
[ ] 11.1 The order of the content did not change OR if the order of the content changed but is still logical.
[ ] 11.2 All relevant content and information from all meaningful images is available.
[ ] 11.3 All content does not overlap and stays legible.
[ ] 11.4 If no confusing elements are revealed on the page.
12. Web: Frames Frames are a means of separating out sections of a web page into different navigable regions
[ ] 12.1 if all frames' Title or Name is descriptive.
13. Web: Repetitive Content and Links - A method must be provided to skip blocks of repeated content or links on Web pages allowing a user to move directly to page-specific content.
[ ] 13.1 There is a method to skip repetitive content.
[ ] 13.2 There is a target for all skip links.
[ ] 13.3 All skip functions work properly
[ ] 13.4 If the relative order of the repeated components is the same as other pages.
14. Web: Required Plug-ins (if no plug-In, then DNA)
[ ] 14.1 if on a public site, links to download all required plug-ins are provided.
[ ] 14.2 All plug-ins required to view content are compliant.

**Comment by ltsheu** [comment]
@davoodharun Per our discussion, please add some Angular magic to get the help buttons and help text working and accessible. Details below.

- We only need to make the help icons/text work on the **Application Page** for now. This work may break the help icons on other pages, but I will remediate as I update patterns on those pages.
- I have pushed my latest updates for the Application Info page to this branch: **lsheu-a11y-fixes-app-info**
- These three areas of App Info have Help Buttons: "What Type of Application Is This?" (form question), "What type of establishment(s) are covered by this request..." (multiple help buttons in a repeater), and "Application Contact Person" (section heading)
- Please see the following punchlist and html examples below:

- [ ] All Help Text blocks start hidden. When clicked, the Help Button should show/hide (toggle) its associated Help Text.  **Note** There is a css rule in forms.scss, line 169 which starts the .dol-help-text divs at display: none.
- [ ] When clicked, the Help Button attribute **aria-expanded** should toggle between false/true. It should start at false. False is for when the Help Text is hidden, True for when the Help Text is shown.
- [ ] The Help Button attribute **aria-controls** should have a value that matches the ID of the associated Help Text div. 
- [ ]  The Help Button should include this attribute/value: **role="tooltip"**
- [ ] The text inside each Help Button should be "Help with this question"
- [ ] There is a link at the top right of the form titled **Show Help for All Items**. This link should toggle all the Help Text on the page open or closed.
- [ ] The App Info form question **What type of establishment(s) are covered by this request for authority to employ workers with disabilities for?** is a repeater. Each checkbox label has a Help Button. The Help Button and Help Text need to work in the same way as other areas of the form. 

HTML example for the new Help Button:
`<button type="button" class="dol-help-link" role="tooltip" aria-controls="[ID of help text div]" aria-expanded="[toggle false/true]">Help with this question</button>`

HTML example for the Help Text block:
`<div id="[ID]" class="dol-help-text">[help text goes here]</div>`

**Comment by ltsheu** [comment]
The work done so far for this user story has been merged into Sprint 1 (PR #288). The work will continue in a new user story during Sprint 2 (new user story #287).

**Comment by jmmcnj** [comment]
@ltsheu Sorry I think this one was set to be 1 of 2, will review the other one, can we close this one too though?

**Comment by ltsheu** [comment]
@davoodharun @jmmcnj  I'm not sure why this was moved back to In Progress? I think this one can be closed since we are continuing work in #287.

**Comment by binwang89** [comment]
@ltsheu tested this user story at azure INT site and found the  Repetitive Content and Links is not working. 
i think there is user story #307 has opened for this issue.
