### ISSUE TITLE
As a user, I would like a beautiful security banner to read before I start using the application

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#388]
This story potentially affected by login/EIN workflow.

Descripition:
In Ref to NIST Control AC-8, WHD approved verbiage will be provided for the warning banner/system use notification, which must be displayed upon accessing the information system.Approving Official”, “Authorizing Official” and “System User”.

Use language provided by Liz in below comment, with functionality similar to cloud.gov (https://login.fr.cloud.gov/login)

## Acceptance Criteria

- [ ] banner functionality must be similar to cloud.gov (https://login.fr.cloud.gov/login)
- [ ] banner page is 508 compliant.

- [ ] DOL header/footer must be present on banner page but not the popup.

### Tasks

- [ ] Implement UX based on functionality described below.
- [ ] Create a UI Dev story that is dependent on this story

### Functionality
- [ ] The banner should come before the user logs into the system (similar to cloud.gov implementation).
- [ ] Banner page shows summary view by default and clicking on details link displays the complete text 
       in a details view. Clicking on "Hide Details" reverts back to summary view. 
       See:  https://login.fr.cloud.gov/login
- [ ] Only upon clicking "AGREE AND CONTINUE" on banner page,  user is redirected to the login page, 

Tasks:
- [ ] Front end implementation of wireframes and messaging
- [ ] Testing for 508 compliance

**Comment by phirefly** [comment]
Closing in favor of #415
