### ISSUE TITLE
Implementation - Create login workflow related pages

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#390]
Specification is from stories #341 #350 #389 #283 
TODO @simplyshang please review the stories above and include the correct ones.
TODO All: Probably best to create individual impl. stories for each page for UX development. 
In addition will need to stories to ensure login flow across these pages (& needs to tie into server side identity framework related logic)....
    - Error page already happens to have a separate visual-design/impl. story

TODO add blocking visual design story to each implementation story to be created...

## Functionality
- [ ] Banner Page - see separate story (#81)
- [ ] User Account Registration Page - redesigned from UXpin link, reuse views from existing login page - Harun/Leslie (#397)
- [ ] Login Page - redesigned from UXpin link with banner, different from registration page (#416)
- [ ] Employer Registration Page - uxping walkthrough (#417)
- [ ] Employer Registration Error Page (#389)
- [ ] 2FA related Page (spec will come from Madhu/David) (#418)

## Acceptance Criteria
 - [ ] Pages are implemented and ready to be wired to server side logic.
 - [ ] Pages are responsive.
 - [ ] Pages are accessible.
 - [ ] Pages conform to the login workflow specified by User Design.

## Accessibility
 - [ ] TODO

**Comment by phirefly** [comment]
Closing this because implementation stories have been created.
