### ISSUE TITLE
Bug: Accessibility: 508: Style sheet dependance (accessibility issue)

### ISSUE THREAD

**Issue by ltsheu** [18F/dol-whd-14c#457]
**Issue identified by DOL accessibility tester:** Programming code or other confusing elements are revealed on the page when CSS is disabled.

**Details:** All pages display extra text, as well as buttons, when CSS toggle is invoked (or CSS disabled). When CSS is disabled, only the text that is seen on the page with CSS-on should be visible.

**Task:** 

When CSS is disabled: 
- [ ] **Hide the Form Menu button**
_Notes:_ It is not clear how to accomplish hiding this, since it is part of the DOM. The Form Menu button is for responsive design. It appears on smaller screens, to toggle the Top Navigation items. 
- [ ] **Hide all the Learn More buttons** 
_Notes:_ It will be difficult to hide the Learn More buttons because they are part of the DOM (which is necessary for screen readers to detect them). Therefore it may be helpful to add a hidden title for each help text that says "Learn More" which only shows when CSS is disabled. This will associate the Help Text with the Help Button when CSS is disabled.
- [ ] **Hide the text "Error Saving Form" (after Saved date/time)**
_Notes:_ JavaScript or API update is needed to remove this from visible DOM
- [ ] **Hide the text "Status Unknown"**
_Notes:_ JavaScript or API update is needed to remove this from visible DOM
- [ ] **Add an underline to Top Nav items to indicate that they are links/clickable**
_Notes:_ Refactor the Top Navigation items to be `<a>` links instead of programmed `<li>`. If they are native `<a>` links, this will help accessibility in general, as well as resolve how the Top Nav items appear when CSS is turned off.
- [ ] **Hide duplicated text in `<legend>` and `<h3>` (the ones that have a help button)**
_Notes:_ The duplicated text is necessary in the case of `<legend>` or `<h3>` that has help buttons, in order to satisfy screen reader accessibility as well as visual design (having the help button flow inline with the text). To remediate this for the Stylesheet Dependence issue, this pattern would need to be visually redesigned and the html pattern re-implemented across the board so that the help icon is not inline with the text.
- [ ] **https://dol-whd-section14c-qa.aisdemos.com/#!/login - all information from Session Expired, Error, Account Creation screens are always displayed**
- [ ] **https://dol-whd-section14c-qa.aisdemos.com/#!/ - "your session will end soon due to inactivity" - is shown all the time.**

## Acceptance Criteria

- [ ] When CSS is disabled on any page, only the text that is seen on the page with CSS-on should be visible.
- [ ] The order of the content changed and is not logical. 
- [ ] Programming code or other confusing elements are revealed on the page.

**Comment by ltsheu** [comment]
@phirefly @mmurthydol  Please see recommendation notes in the user story description.

**Comment by mmurthydol** [comment]
Thanks Leslee!

**Comment by binwang89** [comment]
Update the description for more issues identified by DOL accessibility tester for 508 scan 3.
