### ISSUE TITLE
Admin user management, Audit, User History - continued.

### ISSUE THREAD

**Issue by PrabhakarThummalaDOL** [18F/dol-whd-14c#701]
Below is the list of stories 

#683 - Implement admin functionality to support user management
#78 - As a WHD Security Officer, I would like the application to automatically audits account creation, modification, enabling, disabling, and removal actions, and notifies via email the appropriate personnel.

- [x] User Already Exists check. Remove the Unique constraint for Email-Id and check.
Per Madhu, Identity Framework implementation needs to be customized by use overriding. Deferred. Add a TODO comment to this effect in csharp code.
- [x] add exception handling code to insert into Error log table whether user is enabled/disabled for development troubleshooting purposes.

- [x] Remove “dbo” from the migration code. (Note). (Create new story)
- [x] Do not use “new” for ApplicationDbContext (in the existing code).  For now add TODO comment in code as such.
- [x] Account Controller (New Registration method): Correct/check the Try-Catch blocks.
- [x] Account Controller – Add dependency injection for the UserActivity service.
- [x] UserActivity – the code for inserting data – put the helper code into BaseApiController.
- [x] Change the User Activity Controller API method names to:
      - [x] GetActiveUsers
      - [x] GetCreatedUsers
      - [x] GetUpdatedUsers
      - [x] GetInactiveUsers
      - [x] GetDeletedUsers
- [x] ModifyAccount  method – Make the code block small by using helper methods.
- [x] Test/Check – Try login into the system with a disabled user id.
- [x] IDocumentConcatenate – change the name to IDocumentConcatenateService – also check other places (and classes) too.
- [x] Implement Email functionality if Audit (User Activity) fails. (Part of #78)
- [x] Implement the UserHistory functionality (when Users data changed)
- [x] Email API methods – move the Email API methods to Application Controller (same as PDF concatenate).
- [x] User Activity Controller methods – implement the code (linq) to retrieve Users information.
- [x] UserActivity table – Add new column Role. Foreign key reference to UserRoles table.
- [x] Create new table for UserRoleHistory.
- [x] Admin – User management (#683):
      - [x] Users screen – Scroll to the top if any error. Fixed.
      - [x] Users screen – Error validations implemented.
      - [x] Test code added for Admin user management.
- [x] Phone/Fax/Certification/EIN mask fixed. (#502)

**Comment by mmurthydol** [comment]
Discussed with Prabhakar. 
For sysadmin: Will add the admin buttons (resend email, 2FA verification code, reset pwd, admin change pwd) to User actiivity).

Reset password will be logged not only for sysadmin, but also for non-sysadmin users.
Moving to in progress...
