### ISSUE TITLE
As a WHD Security Officer, I would like the application to  automatically audit account creation, modification, enabling, disabling, and removal actions, and notifies via email the appropriate personnel

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#78]
**Tasks**

- [x] Write new (or rewrite existing) Web API method/s to fulfill account creation/modification audit 
       records. 
      API Methods to create/update/disable/delete.
    Names: ...
    Routing:....
- [x] Use Audit Log tables, Columns: Id, User Id, UserRole, Action (created, updated, enabled, disabled, deleted, undeleted), ActionType (Admin, NonAdmin), CreateAt (DateTimestamp), CreatedBy (nvarchar), UpdatedAt, UpdatedBy.

(or) HACK: In the API methods that create/update/disable/delete,  use a scheme similar to "Login successful" to make entries to ActivityLog table to add enabling, disabling, deleting, & undeleting of audit records in the identity database.
- [x] Write new Web API method/s to report on account creation/modification audit 
       records. 
       API Method Names are for reporting: GetUsersCreated, GetUsersChanged, GetUsersActive, 
      GetUsersInactive, GetUsersDeleted
       Security: Allowed only for "SysAdmin"
- [x] Implement the routing for the WebAPI methods (reporting)
      .../api/admin/audit/users/created
      .../api/admin/audit/users/updated
      .../api/admin/audit/users/active
      .../api/admin/audit/users/inactive
      .../api/admin/audit/users/deleted        
- [x] FYI: Account creation information is available from Users table.
- [x] Results to contain info as outlined below:  (Consider adding UserRole info to results)
.../api/admin/audit/users/created
Email, Name (F+L),  Created DateTime, CreatedBy 

      .../api/admin/audit/users/updated
Email, Name (F+L),  Change DateTime, All-User-Columns (??before & after??) TODO Madhu??

      .../api/admin/audit/users/active
Email, Name (F+L),  Active DateTime 

      .../api/admin/audit/users/inactive
Email, Name (F+L),  Inactive DateTime 

      .../api/admin/audit/users/deleted 
Email, Name (F+L),  Deleted DateTime,

TODO:  Madhu @binwang89 Find out from security why disabling audit records is important.

- [x ] Write API tests. Deferred Per Madhu

**User Activity: Audit**
- [x] Write an API method to audit login/logout functionality (especially  or only for "SysAdmin"). This action is performed by security team by running a security report.
(a) Might need info to see if there was a escalation of privilege attack by a system admin.
(b) Might need to see all login/logout activity of system admin user.
(c) Might need to see all login/logout activity of any user. 

       API Method: GetLoginActivity(UserRole) - filter by userid - query string 
       ToDo: API Method: GetUserActivity(parameter: UserId/Role) - Get the result by joining Role(s) tables.
       .Routing: ../api/admin/log/logins ?role="SysAdmin"
       Results: Email, Name (F+L), UserRole Login DateTime, Logout DateTime

- [x] GetUserActivity(UserId): is typically used by Security to audit system admin activities.
       API Method: api/admin/activities/users/{userid}
  API Method: GetUserActivity(UserRole) - filter by userid - query string 
Security team will review user related actions performed by this particular system admin, or by all system admins (like a, b above in previous requirement).

TODO: Madhu & Prabhakar discuss after initial impl.

Description (Phase 1):
 In Ref to NIST Control AC-2(4), application will automatically audits account creation, modification, enabling, disabling, and removal actions, and notifies via email the appropritate personnel.  Capture notification in an email when certain events happen within the system

Further discussion with DOL security folks, revealed that we should be focused on providing the audit records around account creation, modification, enabling, disabling and removal and that notification to appropriate personnel could be accomplished through a DOL reporting tool.

Tasks:
- [x] Add account creation and modification audit records in identity database
- [x] Add enabling, disabling and removal audit records in the identity database

Acceptance Criteria: Interim AC: team can show the records exist through a database lookup or db schema, long term AC: Report is developed that shows data
Considerations:
1. Application Status
2. Role

**Comment by afrimpong** [comment]
DOL will handle the notification,. However, AIS needs to ensure that the system is capable of capturing the account  creation, modification, enabling, disabling and removal for the notification.

**Comment by bggordon** [comment]
This can be closed based on the responses provided in the other related stories.

**Comment by jmmcnj** [comment]
Closing based on DOLs comments

**Comment by binwang89** [comment]
This user story is not completed.  we need to re- open it again.

**Comment by binwang89** [comment]
"Capture notification in an email when certain events happen within the system" will need additional work and coding. this part is not completed and this user story needs to be re-open.

**Comment by mmurthydol** [comment]
additional work involves two bodies of work (a) changes to MS Identity code (b) notifications need custom not identity based code
