### ISSUE TITLE
Apply style, system feedback, and help/error changes throughout the site. See task list.

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#93]
Descripition:
Change header according to new wireframes, apply style guide, system feedback, help text and error messages, helpfule links slide panel

Tasks:
- [x] Header changes
- [x] style guide implementation to include: styles for buttons, submission feedback, style tile that existed as functionality not including the delete confirmation and system session timeout (note these are captured in other User Stories, session timeout in a security user story and delete confirm in its own)
- [x] add help/show all/text changes
- [x] add unique error messages
- [x] helpful links slide panel

Acceptance Criteria: style changes match wireframes and style guides, system feedback ( to not include delete confirmation or session timeout alert), help text and error messages, helpful links slide panel
Considerations:
1. Application Status
2. Role

**Comment by MrMatt57** [comment]
Styling for session timeout to be captured under https://github.com/18F/dol-whd-14c/issues/76

**Comment by MrMatt57** [comment]
Delete confirmation to be captured under #115

**Comment by jmmcnj** [comment]
Changes still need to be done:
- [ ] fix verbiage in Wage Data - Identify the job or contract on which the most workers were employed at an TO DO: HOURLY/PIECE RATE subminimum wage during the most recently completed fiscal quarter. Provide a brief description of the work performed by workers paid subminimum wages (e.g., Kitchen cleaningâ€”sink, counters, stove, refrigerator, microwave cleaning duties, or Contract No. 123-456 with Sheets Inc.—Laundry Service).

-[ ] make sure all sections show helpful links slide out and show all help shows all help messages thru section

**Comment by mmurthydol** [comment]
@oghaffari Pending changes could be broken down to two separate stories:
1) Fix verbiage sounds like a text edit??
2) Helpful links slide out: This story must become a general UI compliant (508, DOL) help text system for the UI element.

**Comment by mmurthydol** [comment]
Obsolete
